# Staging environment overlay

env.name=staging
ui.baseUrl=https://staging.saucedemo.example.com
petstore.baseUrl=https://staging-petstore.example.com/v2
jsonserver.baseUrl=http://staging-jsonserver:3000
